name: Go Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, darwin]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'
    
    - name: Build
      env:
        GOOS: ${{ matrix.platform }}
        GOARCH: ${{ matrix.arch }}
      run: |
        VERSION=$(git describe --tags --always --dirty)
        COMMIT=$(git rev-parse HEAD)
        DATE=$(date -u +'%Y-%m-%d_%H:%M:%S')
        go build -v -ldflags "-X main.version=${VERSION} -X main.commit=${COMMIT} -X main.date=${DATE}" -o bstore-${{ matrix.platform }}-${{ matrix.arch }} .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bstore-${{ matrix.platform }}-${{ matrix.arch }}
        path: bstore-${{ matrix.platform }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.2.${{ github.run_number }}
        name: Release v0.2.${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          bstore-linux-amd64/bstore-linux-amd64
          bstore-linux-arm64/bstore-linux-arm64
          bstore-darwin-amd64/bstore-darwin-amd64
          bstore-darwin-arm64/bstore-darwin-arm64